services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports: 
      - 3333:3333
    env_file:
      - .env
    command: npm run dev
    environment:
      TZ: UTC
      APP_URL: ${APP_URL}
      APP_PORT: ${APP_PORT}
      APP_SECRET: ${APP_SECRET}
      
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public

      CHOKIDAR_USEPOLLING: 1
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules # This is the only change
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  docker-postgres: